name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          npm install
          cd themes/hexo-theme-butterfly && npm install
      
      - name: Setup Theme
        run: ls themes/hexo-theme-butterfly
        # Theme is already included in the repo, no need to clone
      
      - name: Generate Site
        run: npx hexo clean && npx hexo g
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public